feature(scenario): Allow explicit id for scenario saving, update distinction between create and update
chutney-testing/chutney-kotlin-dsl pull request #109
Opened 2023-08-09 11:26 UTC by DelaunayAlex

Allow explicit id for scenario saving, update distinction between create and update
#### Issue Number
fixes #

#### Describe the changes you've made
Allow explicit id for scenario saving, update distinction between create and update

#### Describe if there is any unusual behaviour of your code 
NA

#### Additional context 

#### Test plan 

#### Checklist

- [ ] Refer to issue(s) the PR solves
- [ ] New kotlin code is covered by tests
- [ ] Add screenshots or gifs of the new behavior, if applicable.
- [ ] All new and existing tests pass
- [ ] No git conflict

2023-08-25 15:41 UTC, KarimGl requested changes

2023-08-25 15:41 UTC, KarimGl commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/synchronize/ChutneyServerServiceImpl.kt
> +        if (scenario.id != null) {
I prefer to have some thing more explicit:
if(new scenario) {
create it
} else {
update it
}

2023-08-29 14:26 UTC, nbrouand reviewed
could you add your use case in tests ?

2023-09-04 13:06 UTC, boddissattva commented on dsl/src/test/kotlin/com/chutneytesting/kotlin/synchronize/ScenarioSynchronizeServiceTest.kt
> +        Assertions.assertThat(resultId).isEqualTo(123)
I feel uneasy with this assertion as this is what the mock has been told to do.
I think the most important here is the assertion, hidden in the mock payload filter, that is the real assertion of this test.

So, either rename bodyRequest in expectedBodyRequest and assert on the mock server expectation id, OR assert the body afterwards with `mockServer.retrieveRecordedRequests`.

2023-09-07 07:37 UTC, boddissattva submitted a review, later dismissed

2023-09-07 14:38 UTC, KarimGl approved these changes

2023-09-07 14:47 UTC, merged