feat(dsl): Add if strategy
chutney-testing/chutney-kotlin-dsl pull request #119
Opened 2023-10-24 08:56 UTC by nbrouand

2023-10-25 07:56 UTC, DelaunayAlex commented on dsl/src/test/kotlin/com/chutneytesting/kotlin/junit/engine/ChutneyTest.kt
> +            When("Updateing values or not depending of strategy") {
Updating

2023-10-25 07:57 UTC, DelaunayAlex requested changes

2023-10-25 07:57 UTC, DelaunayAlex commented on dsl/src/test/kotlin/com/chutneytesting/kotlin/junit/engine/ChutneyTest.kt
> +            When("Updateing values or not depending of strategy") {
Updating

2023-10-26 08:36 UTC, boddissattva submitted a review, later dismissed

2023-10-26 08:46 UTC, KarimGl commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyScenarioDsl.kt
> +    Strategy(type = TYPE, parameters = mapOf("condition" to condition)) {
May be directly type = "if"

2023-10-26 08:46 UTC, KarimGl commented on dsl/src/test/kotlin/com/chutneytesting/kotlin/junit/engine/ChutneyTestEngineTest.kt
>          // 9 times for 9 scenarios in 8 tests methods in ChutneyTest and SameMethodNameClassTest
update or remove comment

2023-10-27 08:03 UTC, boddissattva approved these changes

2023-10-27 09:12 UTC, merged