feat(): Run kotlin style scenarios without chutney server
chutney-testing/chutney-kotlin-dsl pull request #24
Opened 2021-09-27 13:57 UTC by bessonm

2021-09-27 14:14 UTC, boddissattva approved these changes

2021-09-28 13:33 UTC, nbrouand submitted a review, later dismissed

2021-09-29 09:57 UTC, nbrouand requested changes

2021-09-29 09:57 UTC, nbrouand commented on src/main/kotlin/com/chutneytesting/kotlin/launcher/Launcher.kt
> +import org.junit.jupiter.api.Assertions.assertAll
do we really want to be dependant to JUNIT5 ?
Assertj is less impacting as a dependency than junit.

2021-09-30 07:50 UTC, nbrouand approved these changes

2021-09-30 08:01 UTC, merged