feat/junit engine
chutney-testing/chutney-kotlin-dsl pull request #27
Opened 2021-10-22 16:28 UTC by boddissattva

First attempt of JUnit5 engine in Koltin for Kotlin....

2021-11-09 19:16 UTC, nbrouand requested changes

2021-12-16 16:31 UTC, bessonm requested changes
I'm ok with most of the code except its file organization.
There are 2 classes "ExecutionUtils" one plural, one singular.

ReportWriter and ExecutionService are shared between Launcher and Engine.

Overall understanding and reading is not the best.
I feel like Kotlin is to easy to clutter.

We should also remove all wildcard imports, it doesn't help to improve reading since we cannot get a glance at dependencies.

2021-12-16 16:31 UTC, bessonm commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/launcher/ExecutionUtils.kt
> +object ReportWriter {
ReportWriter is used by the Launcher and the JUnit engine.
Being buried here in launcher package in an "util" class doesn't feel right

2022-03-22 12:26 UTC, bessonm commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/junit/engine/ChutneyExecutionContexts.kt
> +    private fun executionStatus(): Status {
unused method, still relevant ?

2022-03-22 12:26 UTC, bessonm commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/execution/report/SiteGenerator.kt
> +package com.chutneytesting.kotlin.execution.report
l.70 there is commented code we can delete

2022-03-22 12:26 UTC, bessonm commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/junit/engine/ChutneyExecutionContexts.kt
> +            TestExecutionResult.successful() // global status could be executionStatus() but brings some integration problems with ide
I don't understand those lines. Is it really used for something ? I don't see any different behavior when removing them

2022-03-24 13:44 UTC, nbrouand commented
I would like to add in test a junit properties file with all configurable properties to be able to play easily with in our projet

2022-03-24 14:41 UTC, nbrouand commented
Comment for futur upgrade : 
 - Manage "Rerun failed test"
 - Click in left menu redirect to the scenario, or the step

2022-03-28 15:11 UTC, nbrouand approved these changes

2022-03-29 07:52 UTC, bessonm approved these changes

2022-03-29 07:53 UTC, merged