chore/json compare mode
chutney-testing/chutney-kotlin-dsl pull request #45
Opened 2022-02-09 16:02 UTC by boddissattva

#### Describe the changes you've made

Add comparison mode to json compare task

#### Checklist

- [ ] Refer to issue(s) the PR solves
- [ ] New kotlin code is covered by tests
- [ ] Add screenshots or gifs of the new behavior, if applicable.
- [x] All new and existing tests pass
- [x] No git conflict

2022-02-10 08:36 UTC, KarimGl approved these changes
it's ok for me

2022-02-11 10:53 UTC, nbrouand requested changes

2022-02-11 10:53 UTC, nbrouand commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
> +    mode: String? = null
aggre

2022-02-24 10:54 UTC, boddissattva commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
> +    mode: String? = null
done

2022-02-24 14:39 UTC, nbrouand approved these changes

2022-02-24 15:10 UTC, merged