chore: documentation of task output
chutney-testing/chutney-kotlin-dsl pull request #60
Opened 2022-07-05 16:40 UTC by nbrouand

2022-07-06 11:14 UTC, bessonm commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
> + * Log variables of the execution context
Log values in the execution context ?

2022-07-06 11:14 UTC, bessonm commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
> +// fun ChutneyStepBuilder.HttpsServerStopTask auto registered by start task
why not add this comment to the previous block ?

2022-07-06 11:14 UTC, bessonm commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
> + * Selenium resize brower
browser typo

2022-07-06 14:25 UTC, boddissattva commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
> + * Wait "5 min", "300 sec" or "500 ms" time
Add example with until xxxx form maybe

2022-07-06 14:26 UTC, boddissattva commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
> + * Add a final task, execute at the end of the execution
... in a teardown final step

2022-07-06 14:36 UTC, boddissattva commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
> + * @output payload : the payload sent  (String)
Remove @output.

2022-07-07 08:15 UTC, boddissattva requested changes

2022-07-07 08:15 UTC, boddissattva commented on dsl/src/main/kotlin/com/chutneytesting/kotlin/dsl/ChutneyStepImplExtensions.kt
> + * Compare two String on multiple mode (equals, not-equals, contains, not-contains, greater-than, less-than
close parenthesis.
For greater and less comparator, numerics are expected.

2022-07-08 12:45 UTC, merged