chore(example): add kafka scenario example
chutney-testing/chutney-kotlin-dsl pull request #91
Opened 2023-02-06 18:09 UTC by rbenyoussef

#### Issue Number
fixes #

#### Describe the changes you've made

#### Describe if there is any unusual behaviour of your code 

#### Additional context 

#### Test plan 

#### Checklist

- [ ] Refer to issue(s) the PR solves
- [ ] New kotlin code is covered by tests
- [ ] Add screenshots or gifs of the new behavior, if applicable.
- [ ] All new and existing tests pass
- [ ] No git conflict

2023-02-08 17:36 UTC, bessonm requested changes

2023-02-08 17:36 UTC, bessonm commented on example/src/test/kotlin/kafka/KafkaTest.kt
> +            ).build()
Why not use the DSL ?

``` kotlin
val environment = ChutneyEnvironment(
    name = "Global",
    description = "Default environment",
    targets = listOf(
        ChutneyTarget(
            name = "target",
            url = kafkaContainer.bootstrapServers,
            properties = mapOf("auto.offset.reset" to "earliest")
        )
    )
)
```

2023-02-09 18:59 UTC, rbenyoussef commented on example/src/test/kotlin/kafka/KafkaTest.kt
> +            ).build()
Done!

2023-02-10 08:54 UTC, nbrouand approved these changes

2023-02-10 08:59 UTC, merged